# Generated by Django 2.1.7 on 2019-09-06 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('sex', models.BooleanField()),
                ('age', models.SmallIntegerField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('live', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('mark', models.TextField(max_length=100)),
            ],
        ),
    ]
