# Generated by Django 2.1.7 on 2019-10-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cardsmsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50)),
                ('cardnumber', models.CharField(max_length=30)),
                ('usepassword', models.CharField(max_length=11)),
                ('mark', models.CharField(max_length=100)),
            ],
        ),
    ]
